services:
  mongo:
    image: mongo:7
    container_name: bootcamp_mongo_auth
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: bootcamp
      MONGO_INITDB_ROOT_PASSWORD: bootcamp123
      MONGO_INITDB_DATABASE: bootcamp_auth_dev
    ports:
      - "27019:27017"
    volumes:
      - mongo_auth_data:/data/db

volumes:
  mongo_auth_data:
